### ISSUE TITLE
Error when running the Python script

### ISSUE THREAD

**Issue by CursedAtom** [FemboyNova/Salad-Info-Extractor#3]
[error.txt](https://github.com/FemboyNova/Salad-Info-Extractor/files/13622418/error.txt)

This error is after the text `SGS Bandwidth Usage/Errors (Updated Data):` and before the table for bandwidth starts. I have already run `pip install asyncio` just to see if it would fix the issue, but it did not. 

Error was preset before I installed asyncio. Fresh windows install with this script (and dependencies) being the only python ever run on this install. Error is periodic and I can't really find where it's coming from.

In line 22 of the sgs log, you will see an error that lines up with the timing of the error in Salad Info Extractor:

`2023-12-08 20:30:30.651 -05:00 [INF] {"level":"error","ts":1702085430.6512306,"caller":"ingress/api-client.go:341","msg":"95adff9a-f384-455b-a216-90c161654a30: Cannot dial hot ready: context deadline exceeded","stacktrace":"github.com/SaladTechnologies/sgs/pkg/ingress.CreateHotreadyStreamConnection\n\tC:/Users/ericn/Documents/Projects/salad-gateway-service/go/pkg/ingress/api-client.go:341\ngithub.com/SaladTechnologies/sgs/pkg/ingress.ConnectToSGSServer.func5.1\n\tC:/Users/ericn/Documents/Projects/salad-gateway-service/go/pkg/ingress/api-client.go:291\ngithub.com/SaladTechnologies/sgs/pkg/ingress.ConnectToSGSServer.func5\n\tC:/Users/ericn/Documents/Projects/salad-gateway-service/go/pkg/ingress/api-client.go:297"}`

[sgs-log.log](https://github.com/FemboyNova/Salad-Info-Extractor/files/13622432/sgs-log.log)

Pc Info:

Python 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)] on win32
Processor: Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz   4.10 GHz
Ram: 48.0 GB (47.9 GB usable)

Edition	Windows 11 Pro
Version	22H2
Installed on	‎02/‎12/‎2023
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

**Comment by CursedAtom** [comment]
Adding on to this, the error appears every time the sgs error is in the logs.

**Comment by FemboyNova** [comment]
Issue is now fixed, was due to the discord rpc shitting itself (creating multiple instances)
